name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.INSTANCE_HOST }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${SSH_PRIVATE_KEY} '
            
            if ls | grep ga-demo-html; then 
              sudo rm -rf ga-demo-html
            fi
      
            sudo git clone https://github.com/IshThumber/ga-demo-html.git
      
            sudo rm /var/www/html/*.html
      
            sudo mv ga-demo-html/index.html /var/www/html/
      
            sudo systemctl restart apache2
          '

