name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${SSH_PRIVATE_KEY} '
            
            if ls | grep nginx; then 
              sudo rm -rf nginx
            fi
      
            sudo git clone https://github.com/sathwika46/nginx.git
      
            sudo rm /var/www/html/*.html
      
            sudo mv nginx/index.html /var/www/html/
      
            sudo systemctl restart apache2
          '

